// Shared series list used by album, game (and others). Edit here to keep them in sync.
export const seriesList = [
  { title: 'Final Fantasy I', value: 'Final Fantasy I' },
  { title: 'Final Fantasy II', value: 'Final Fantasy II' },
  { title: 'Final Fantasy III', value: 'Final Fantasy III' },
  { title: 'Final Fantasy IV', value: 'Final Fantasy IV' },
  { title: 'Final Fantasy V', value: 'Final Fantasy V' },
  { title: 'Final Fantasy VI', value: 'Final Fantasy VI' },
  { title: 'Final Fantasy VII', value: 'Final Fantasy VII' },
  { title: 'Final Fantasy VII Remake', value: 'Final Fantasy VII Remake' },
  { title: 'Final Fantasy VII Rebirth', value: 'Final Fantasy VII Rebirth' },
  { title: 'Final Fantasy VIII', value: 'Final Fantasy VIII' },
  { title: 'Final Fantasy IX', value: 'Final Fantasy IX' },
  { title: 'Final Fantasy X', value: 'Final Fantasy X' },
  { title: 'Final Fantasy XI', value: 'Final Fantasy XI' },
  { title: 'Final Fantasy XII', value: 'Final Fantasy XII' },
  { title: 'Final Fantasy XIII', value: 'Final Fantasy XIII' },
  { title: 'Final Fantasy XIV', value: 'Final Fantasy XIV' },
  { title: 'Final Fantasy XV', value: 'Final Fantasy XV' },
  { title: 'Final Fantasy XVI', value: 'Final Fantasy XVI' },
  { title: 'Final Fantasy Tactics', value: 'Final Fantasy Tactics' },
  { title: 'Final Fantasy Crystal Chronicles', value: 'Final Fantasy Crystal Chronicles' },
  { title: 'Dissidia Final Fantasy', value: 'Dissidia Final Fantasy' },
  { title: 'Theatrhythm Final Fantasy', value: 'Theatrhythm Final Fantasy' },
  { title: 'Chocobo', value: 'Chocobo' },
  { title: 'The Black Mages', value: 'The Black Mages' },
  { title: 'Distant Worlds', value: 'Distant Worlds' },
  { title: 'Piano Collections', value: 'Piano Collections' },
  { title: 'BRA★BRA Final Fantasy', value: 'BRA★BRA Final Fantasy' },
  { title: 'Other', value: 'Other' },
]